services:
  localstack:
    image: localstack/localstack:latest
    container_name: localstack
    ports:
      - "4566:4566"          # unified edge port
    environment:
      - LOCALSTACK_SERVICES=cloudformation,sts,s3,sqs,dynamodb,ssm,events,logs,iam,lambda
      - LOCALSTACK_PERSISTENCE=1
    volumes:
      - localstack_data:/var/lib/localstack
      - "/var/run/docker.sock:/var/run/docker.sock"

  mongo:
    image: mongo:6.0
    container_name: nalukataq-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nalukataq-app
    working_dir: /app
    command: npm run offline
    ports:
      - "3000:3000"
    # env_file:
    #   - .env.dev
    volumes:
      - ./:/app 
    depends_on:
      - localstack
      - mongo

volumes:
  mongo_data:
  localstack_data: