/**
 * A list of all application-level error codes.
 */
export enum ErrorCode {
  MISSING_BODY = 'MISSING_BODY',
  INVALID_BASE64 = 'INVALID_BASE64',
  MALFORMED_URLENCODED = 'MALFORMED_URLENCODED',
  MISSING_TWILIO_FIELD = 'MISSING_TWILIO_FIELD',
  INTERNAL_SERVER_ERROR = 'INTERNAL_SERVER_ERROR',
  PROCESSING_LOCK_TAKEN = 'PROCESSING_LOCK_TAKEN',
  INVALID_PHONE_NUMBER_FORMAT = 'INVALID_PHONE_NUMBER_FORMAT',
  MISSING_ENV_VARIABE = 'MISSING_ENV_VARIABLE',
  DUPLICATE_USER_PROFILE = 'DUPLICATE_USER_PROFILE',
  OUTGOING_MESSAGE_EMPTY_CONTENT = 'OUTGOING_MESSAGE_EMPTY_CONTENT',
  DUPLICATE_CAMPAIGN = "DUPLICATE_CAMPAIGN",
}
