/**
 * A list of all application-level error codes.
 */
export enum ErrorCode {
  MISSING_BODY = 'MISSING_BODY',
  INVALID_BASE64 = 'INVALID_BASE64',
  MALFORMED_URLENCODED = 'MALFORMED_URLENCODED',
  MISSING_TWILIO_FIELD = 'MISSING_TWILIO_FIELD',
  INTERNAL_SERVER_ERROR = 'INTERNAL_SERVER_ERROR',
}
