import { injectable } from 'tsyringe';
import { ICampaignSubmissionRepository } from './ICampaignSubmissionRepository';
import {
  CampaignSubmissionModel,
  ICampaignSubmission,
  ICampaignSubmissionDocument,
} from '../models/CampaignSubmission';
import { MongoServerError } from 'mongodb';
import { MONGO_ERROR_CODES } from '../libs/errors/MongoErrorCodes';
import { IMedia } from '../models/Media';

@injectable()
export class CampaignSubmissionRepository implements ICampaignSubmissionRepository {
  /**
   * Creates a new campaign submission record for a user.
   * The _id will be autogenerated by MongoDB and returned as part of the ISubmission object.
   *
   * @param campaignId The ID of the campaign.
   * @param phoneNumber The user's phone number.
   * @returns A Promise that resolves with the created submission document (including its _id).
   * @throws Error if creation fails.
   */
  public async createSubmission(
    campaignId: string,
    phoneNumber: string,
  ): Promise<ICampaignSubmission> {
    try {
      const newSubmission: ICampaignSubmissionDocument = new CampaignSubmissionModel({
        user: phoneNumber,
        campaign: campaignId,
      });
      const createdSubmission: ICampaignSubmissionDocument = await newSubmission.save();
      console.log(
        `CampaignSubmissionRepository :: Created submission ${createdSubmission.id} for ${phoneNumber} in campaign ${campaignId}.`,
      );
      return createdSubmission;
    } catch (error: unknown) {
      if (error instanceof MongoServerError && error.code === MONGO_ERROR_CODES.DUPLICATE_KEY) {
        console.warn(
          `CampaignSubmissionRepository :: Duplicate entry for user ${phoneNumber} in campaign ${campaignId}. Error:`,
          error.message,
        );
      }
      console.error(
        `CampaignSubmissionRepository :: Error creating submission for ${phoneNumber} in ${campaignId}:`,
        error,
      );
      throw error;
    }
  }

  /**
   * Adds or updates a specific response field within an existing campaign submission.
   * This updates the 'submission_data' Map.
   *
   * @param submissionId The _id of the submission record (autogenerated ObjectId).
   * @param fieldName The name of the field to add/update (e.g., 'inupiat_value').
   * @param value The value of the response (expected to be a string).
   * @returns A Promise that resolves when the response is added.
   * @throws Error if the submission record is not found or update fails.
   */
  public async addTextResponse(
    submissionId: string,
    fieldName: string,
    value: string,
  ): Promise<void> {
    try {
      const updateResult: ICampaignSubmissionDocument | null =
        await CampaignSubmissionModel.findByIdAndUpdate(
          submissionId,
          { $set: { [`submission_data.${fieldName}`]: value } },
          { new: true, runValidators: true, upsert: false },
        ).exec();

      if (!updateResult) {
        console.warn(
          `CampaignSubmissionRepository :: Submission record ${submissionId} not found for adding response to ${fieldName}.`,
        );
        throw new Error(`Campaign submission ${submissionId} not found.`);
      }
      console.log(
        `CampaignSubmissionRepository :: Added response for submission ${submissionId}, field '${fieldName}'.`,
      );
    } catch (error) {
      console.error(
        `CampaignSubmissionRepository :: Error adding response for submission ${submissionId}, field ${fieldName}:`,
        error,
      );
      throw error;
    }
  }

  /**
   * Adds media data to an existing campaign submission.
   * This updates the 'media_data' Map in the Submission document.
   * The key in the map will be the 'key' property of the IMedia object (e.g., S3 object key).
   *
   * @param submissionId The _id of the submission record.
   * @param media The IMedia object to add to the media_data Map.
   * @returns A Promise that resolves when the media is added.
   * @throws Error if the submission record is not found or update fails.
   */
  public async addOrUpdateMediaToSubmission(submissionId: string, media: IMedia): Promise<void> {
    const mediaMapKey = media.key;
    try {
      const updateResult: ICampaignSubmissionDocument | null =
        await CampaignSubmissionModel.findByIdAndUpdate(
          submissionId,
          { $set: { [`media_data.${mediaMapKey}`]: media } },
          { new: true, runValidators: true, upsert: false },
        ).exec();

      if (!updateResult) {
        console.error(
          `CampaignSubmissionRepository :: Submission record ${submissionId} not found for adding media.`,
        );
        throw new Error(`Campaign submission ${submissionId} not found.`);
      }
      console.log(
        `CampaignSubmissionRepository :: Added media '${mediaMapKey}' to submission ${submissionId}.`,
      );
    } catch (error) {
      console.error(
        `CampaignSubmissionRepository :: Error adding media to submission ${submissionId}:`,
        error,
      );
      throw error;
    }
  }

  /**
   * Adds or updates multiple media items' metadata within an existing campaign submission.
   * This updates/sets multiple keys within the 'media_data' Map.
   *
   * @param submissionId The ID of the submission record.
   * @param mediaItems An array of IMedia objects to add or update. Each IMedia must have a unique 'key'.
   * @returns A Promise that resolves when the media data is updated.
   * @throws Error if the submission record is not found, a media item is missing a key, or update fails.
   */
  public async addOrUpdateMultipleMediaToSubmission(
    submissionId: string,
    mediaItems: IMedia[],
  ): Promise<void> {
    if (!mediaItems || mediaItems.length === 0) {
      console.warn(
        `CampaignSubmissionRepository :: No media items provided for submission ${submissionId}.`,
      );
      return;
    }

    const updateSet: Record<string, IMedia> = {};
    for (const media of mediaItems) {
      updateSet[`media_data.${media.key}`] = media;
    }

    try {
      const updateResult: ICampaignSubmissionDocument | null =
        await CampaignSubmissionModel.findByIdAndUpdate(
          submissionId,
          { $set: updateSet },
          { new: true, runValidators: true, upsert: false },
        ).exec();

      if (!updateResult) {
        console.error(
          `CampaignSubmissionRepository :: Submission record ${submissionId} not found for adding multiple media.`,
        );
        throw new Error(`Campaign submission ${submissionId} not found.`);
      }
      console.log(
        `CampaignSubmissionRepository :: Added/updated ${mediaItems.length} media items to submission ${submissionId}.`,
      );
    } catch (error) {
      console.error(
        `CampaignSubmissionRepository :: Error adding/updating multiple media for submission ${submissionId}:`,
        error,
      );
      throw error;
    }
  }
}
